version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.2
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.3.2
    container_name: kafka
    ports:
      - "9092:9092" # For clients running outside docker (e.g. local Python scripts)
      - "29092:29092" # For clients running inside other docker containers
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0 # Optional: Speeds up consumer group joining for development
      KAFKA_CREATE_TOPICS: "test-topic:1:1" # Automatically creates 'test-topic' with 1 partition and replication factor 1
      # You might want more partitions for better parallelism demonstration, e.g., "test-topic:3:1" for 3 partitions
      # If you change the number of partitions, ensure your consumer logic can handle it or re-evaluate partition assignment.

networks:
  default:
    name: kafka-net
